(defun color-theme-raminho ()
  (interactive)
  (color-theme-install
   '(color-theme-raminho
      ((background-color . "#1c1c1c")
      (background-mode . light)
      (border-color . "#000000")
      (cursor-color . "#c3a2a2")
      (foreground-color . "#bdbdbd")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "#000000" :background "#6c5656"))))
     (region ((t (:background "#4d4d4d"))))
     (font-lock-builtin-face ((t (:foreground "#37c0c8"))))
     (font-lock-comment-face ((t (:foreground "#6b6b6b"))))
     (font-lock-function-name-face ((t (:foreground "#9c6868"))))
     (font-lock-keyword-face ((t (:foreground "#c48b36"))))
     (font-lock-string-face ((t (:foreground "#93b36b"))))
     (font-lock-type-face ((t (:foreground"#ff5ce1"))))
     (font-lock-variable-name-face ((t (:foreground "#919021"))))
     (minibuffer-prompt ((t (:foreground "#5581f7" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide color-theme-raminho)